/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#20201f",
        "on-primary": "#2a3400",
        "surface-variant": "#353535",
        "tertiary-container": "#e2e2e2",
        "inverse-surface": "#e5e2e1",
        "primary-container": "#caf300",
        secondary: "#c6c6c6",
        "on-secondary": "#303030",
        surface: "#131313",
        tertiary: "#ffffff",
        "on-background": "#e5e2e1",
        "surface-bright": "#393939",
        "primary-fixed-dim": "#b0d500",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-highest": "#353535",
        primary: "#ffffff",
        "on-primary-fixed": "#171e00",
        background: "#131313",
        "on-surface-variant": "#c5c9ac",
        "surface-container-low": "#1c1b1b",
        "surface-container-high": "#2a2a2a",
        "primary-fixed": "#caf300",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        xs: "8px",
        lg: "48px",
        xl: "80px",
        "margin-desktop": "40px",
        md: "24px",
        sm: "16px",
        gutter: "20px",
        base: "4px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-xl": ["Montserrat", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["80px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "900" }],
        "headline-md": ["24px", { lineHeight: "28px", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["48px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
